export const directoryCopy = {
    title: '业务地图',
    list: '名录',
    search: '搜索小区、物业或街道',
    district: '区县',
    street: '街道',
    all: '全部',
    empty: '还没有名录。请导入小区资料。',
    import: '导入名录',
    households: '户',
    unknown: '待补充',
    source: '来源',
    company: '物业企业',
    manager: '物业项目经理',
    phone: '电话',
    community: '社区',
    communications: '沟通记录',
    addCommunication: '记一次沟通',
    demand: '需求',
    result: '沟通结果',
    nextStep: '下一步',
    contact: '联系人',
    contactRole: '身份',
    occurredOn: '日期',
    status: '状态',
    save: '保存',
    loadFailed: '名录加载失败。',
    importFailed: '名录导入失败。',
    importOk: '已导入',
    conflicts: '待核对',
    conflictHint: '同名但规模或分期不同，请分别核对。',
    reviewConflicts: '查看待核对',
    confirmLink: '确认为同一档案',
    keepSeparate: '保持分档',
    conflictOpen: '待处理',
    incomingScale: '本次',
    existingScale: '已有',
    incomingCompany: '本次物业',
    existingCompany: '已有物业',
    staffFinance: '财务明细仅老板与股东可见。已确定的项目金额在项目页查看。',
    convert: '转为会务项目',
    converted: '已建立项目',
    openProject: '打开已关联项目',
    newEngagement: '为新委托建项目',
}

export const communicationStatusLabel = {
    LEARNING: '待了解',
    CONTACTING: '接洽中',
    COMMISSIONED: '已确定委托',
    PAUSED: '暂缓',
    DROPPED: '未推进',
} as const
