export const driveCopy = {
    title: '网盘',
    upload: '上传',
    name: '名称',
    size: '大小',
    date: '日期',
    uploader: '上传者',
    failed: '未通过',
    newFolder: '新建目录',
    move: '移动',
    rename: '重命名',
    remove: '删除',
    removeConfirm: '删除后不可恢复。',
    empty: '这个目录是空的',
    unconfigured: '上传未配置',
    create: '创建',
    confirm: '确定',
    confirmMove: '放到这里',
    download: '下载',
    newSubfolder: '新建子目录',
    targetFolder: '目标目录',
    scanning: '扫描中',
    infected: '检测到风险，文件不可下载',
    scanFailed: '扫描失败，文件不可下载，请重新上传',
    stillScanning: '文件仍在扫描中。',
    crumbs: '目录',
    createFailed: '无法创建目录。',
    renameFailed: '无法重命名。',
    deleteFailed: '无法删除文件。',
    moveFailed: '无法移动文件。',
    uploading: '上传中',
    uploadingEllipsis: '上传中…',
    tooLarge: '文件超过 100MB 上限。',
    emptyFile: '请选择非空文件。',
    unsupportedType: '不支持的文件类型。',
}

export function uploadingPercent(percent: number): string {
    return `${driveCopy.uploading} ${percent}%`
}
