export const driveCopy = {
    title: '网盘',
    upload: '上传',
    name: '名称',
    size: '大小',
    date: '日期',
    uploader: '上传者',
    failed: '未通过',
    newFolder: '新建目录',
    move: '移动',
    rename: '重命名',
    remove: '删除',
    removeConfirm: '删除后不可恢复。',
    empty: '这个目录是空的',
    unconfigured: '上传未配置',
    create: '创建',
    confirm: '确定',
    confirmMove: '确定移动',
    download: '下载',
    newSubfolder: '新建子目录',
    targetFolder: '目标目录',
    scanning: '扫描中',
    infected: '检测到风险，文件不可下载',
    scanFailed: '扫描失败，文件不可下载，请重新上传',
    stillScanning: '文件仍在扫描中，请稍后重试。',
}
