export const financeCopy = {
    title: '财务',
    record: '记一笔',
    export: '导出',
    companyCost: '公司运营成本',
    projectCost: '项目成本',
    income: '收入',
    margin: '毛利',
    date: '日期',
    kind: '类型',
    scope: '范围',
    project: '项目',
    category: '类别',
    memo: '备注',
    amount: '金额',
    visibility: '可见',
    adjust: '调整',
    reason: '原因',
    save: '保存',
    empty: '本月还没有记录',
    defaultVisibility: '默认：管理层',
    pivot: '项目 × 月',
    month: '月份',
}
