export const financeCopy = {
    title: '财务',
    record: '记一笔',
    export: '导出',
    companyCost: '公司运营成本',
    projectCost: '项目成本',
    income: '收入',
    margin: '毛利',
    date: '日期',
    kind: '类型',
    scope: '范围',
    project: '项目',
    category: '类别',
    memo: '备注',
    amount: '金额',
    amountYuan: '金额（元）',
    visibility: '可见',
    adjust: '调整',
    reason: '原因',
    save: '保存',
    empty: '本月还没有记录',
    defaultVisibility: '默认：管理层',
    pivot: '项目 × 月',
    month: '月份',
    amountAndCategory: '请填写金额和类别。',
    projectRequired: '项目成本需要选择项目。',
    adjustRequired: '请填写调整后的值和原因。',
    adjustAmountInvalid: '调整金额无效。',
    adjustValue: '调整后的值',
    adjustReason: '调整原因',
}

export function financeMonthLabel(year: string, month: string): string {
    return `${year}年${Number(month)}月`
}
