export const financeCopy = {
    title: '财务',
    record: '记一笔',
    export: '导出',
    companyCost: '公司运营成本',
    projectCost: '项目成本',
    income: '收入',
    margin: '毛利',
    date: '日期',
    kind: '类型',
    scope: '范围',
    project: '项目',
    category: '类别',
    memo: '备注',
    amount: '金额',
    amountYuan: '金额（元）',
    visibility: '可见',
    adjust: '调整',
    reason: '原因',
    save: '保存',
    empty: '本月还没有记录',
    staffRestricted: '财务明细仅老板与股东可见。已确定的项目金额在项目页查看。',
    defaultVisibility: '默认：管理层',
    pivot: '项目 × 月',
    month: '月份',
    amountAndCategory: '请填写金额和类别。',
    projectRequired: '项目成本需要选择项目。',
    adjustRequired: '请填写调整后的值和原因。',
    adjustAmountInvalid: '调整金额无效。',
    adjustValue: '调整后的值',
    adjustReason: '调整原因',
    importBatch: '导入账本',
    markPaid: '登记付款',
    payAmount: '付款金额（元）',
    payDate: '付款日期',
    paidTotal: '已付',
    unpaidTotal: '未付',
    importPending: '待处理明细',
    importSuccess: '已入账行',
    monthCost: '本月固定开支',
    saveMonth: '登记固定开支',
    paid: '已付',
    unpaid: '未付',
    batchReplay: '同一批次已处理。',
    importInserted: '新入账',
    importOpenEntry: '打开账目',
    confirmSame: '确认为同一笔并补凭证',
    insertIndependent: '作为独立费用入账',
    payRetryHint: '上一笔付款结果尚未确认，将使用原登记键恢复。',
    payNew: '改为登记新一笔',
    payClose: '关闭',
    candidateMemo: '候选备注',
    candidateVoucher: '候选凭证',
    payKeyMismatch: '该付款键已登记不同金额或日期，已保留原结果。',
    payRestoredOriginal: '已恢复原付款结果，未使用修改后的金额或日期。',
    retryOriginalBatch: '按原批次重试此行',
    importMore: '查看更多待处理',
    importMoreProcessed: '查看更多已入账来源',
    processedSources: '已处理来源',
    voucherConflict: '目标账目已有其他凭证，不能再补这一张。',
    confirmCandidate: '确认该候选',
}

export function financeMonthLabel(year: string, month: string): string {
    return `${year}年${Number(month)}月`
}
