export const projectsCopy = {
    title: '项目',
    create: '新建',
    edit: '编辑',
    active: '进行中',
    archived: '已归档',
    milestones: '里程碑',
    add: '添加',
    name: '名称',
    stage: '阶段',
    start: '立项开始日',
    due: '合同到期日',
    processDue: '流程结束日',
    description: '说明',
    save: '保存',
    done: '完成',
    empty: '还没有项目',
    emptyMilestones: '还没有里程碑',
    remove: '删除',
    archiveAction: '归档',
    deleteConfirm: '删除后不可恢复。有记账的项目不能删。',
    confirm: '确定',
    close: '关闭',
    nameLabel: '项目名称',
    tooLong: '项目名称不能超过 255 个字符。',
    loadFailed: '项目列表加载失败。',
    nameRequired: '请输入项目名称。',
    createSubmit: '保存',
    undone: '取消完成',
    serviceFee: '项目金额',
    nodes: '阶段节点',
    shift: '调期',
    completeStage: '确认完成',
    shiftDays: '天数',
    shiftReason: '原因',
    evidence: '完成材料',
    materialsRequired: '该节点需要定稿或公示材料后才能完成。',
    lead: '主负责人',
    feeYuan: '项目金额（元）',
    changes: '调期记录',
    preparation: '准备事项',
    document: '对应文件',
    applyWorkflow: '应用默认流程',
    completeService: '确认服务完成',
    evidenceFileId: '已上传文件 ID',
    evidenceAdd: '再关联一份材料',
    evidenceLinked: '已关联材料',
    materialsHint: '请分别关联文档和照片等真实文件，不要把多个 ID 填在同一格。',
    pendingWorkflow: '待排期',
    nodesDone: '节点已完成',
    serviceDone: '服务已完成',
}
