export const projectsCopy = {
    title: '项目',
    create: '新建',
    edit: '编辑',
    active: '进行中',
    archived: '已归档',
    milestones: '里程碑',
    add: '添加',
    name: '名称',
    stage: '阶段',
    start: '开始',
    due: '到期',
    description: '说明',
    save: '保存',
    done: '完成',
    empty: '还没有项目',
    emptyMilestones: '还没有里程碑',
    nameLabel: '项目名称',
    tooLong: '项目名称不能超过 255 个字符。',
    loadFailed: '项目列表加载失败。',
    nameRequired: '请输入项目名称。',
}
