Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
StreamMaxLength 100M
MaxScanSize 100M
MaxFileSize 100M
MaxRecursion 16
MaxFiles 10000
ReadTimeout 30
CommandReadTimeout 5
SendBufTimeout 60
ExitOnOOM yes
ScanArchive yes
