"""PostgreSQL schema constraints for identity and project membership."""

import asyncio
import os
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import asyncpg
import pytest
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.schema import CreateIndex

from superboss.modules.projects.models import Project, ProjectMember
from superboss.modules.users.models import Role, User, UserStatus

SERVER_ROOT = Path(__file__).resolve().parents[2]


def _temporary_database_url(database_url: str, database_name: str) -> str:
    parsed = urlsplit(database_url)
    return urlunsplit((parsed.scheme, parsed.netloc, f"/{database_name}", "", ""))


def test_pristine_0002_upgrade_head_and_downgrade_restore_exact_schema(
    postgres_database: str,
) -> None:
    """Revision 0003 must run from the real 0002 schema and undo only its own objects."""
    temporary_name = f"superboss_pristine_{uuid4().hex}"
    admin_url = _temporary_database_url(postgres_database, "postgres")
    temporary_url = _temporary_database_url(postgres_database, temporary_name)

    async def create_database() -> None:
        connection = await asyncpg.connect(admin_url.replace("postgresql+asyncpg", "postgresql"))
        try:
            await connection.execute(f'CREATE DATABASE "{temporary_name}"')
        finally:
            await connection.close()

    async def drop_database() -> None:
        connection = await asyncpg.connect(admin_url.replace("postgresql+asyncpg", "postgresql"))
        try:
            await connection.execute(f'DROP DATABASE IF EXISTS "{temporary_name}" WITH (FORCE)')
        finally:
            await connection.close()

    asyncio.run(create_database())
    environment = os.environ.copy()
    environment["SUPERBOSS_DATABASE_URL"] = temporary_url
    try:
        for revision in ("0002_auth_sessions", "head"):
            subprocess.run(
                [sys.executable, "-m", "alembic", "upgrade", revision],
                cwd=SERVER_ROOT,
                env=environment,
                check=True,
            )

        async def head_catalog() -> tuple[bool, bool]:
            connection = await asyncpg.connect(temporary_url.replace("postgresql+asyncpg", "postgresql"))
            try:
                index = await connection.fetchval(
                    "SELECT indexdef FROM pg_indexes WHERE indexname = 'uq_projects_name_ci'"
                )
                checks = await connection.fetchval(
                    "SELECT count(*) FROM pg_constraint WHERE conname IN "
                    "('ck_projects_name_trimmed', 'ck_projects_name_length')"
                )
                return "lower(" in str(index) and "name" in str(index), checks == 2
            finally:
                await connection.close()

        assert asyncio.run(head_catalog()) == (True, True)
        subprocess.run(
            [sys.executable, "-m", "alembic", "downgrade", "0002_auth_sessions"],
            cwd=SERVER_ROOT,
            env=environment,
            check=True,
        )

        async def base_catalog() -> tuple[int, int]:
            connection = await asyncpg.connect(temporary_url.replace("postgresql+asyncpg", "postgresql"))
            try:
                index_count = await connection.fetchval(
                    "SELECT count(*) FROM pg_indexes WHERE indexname = 'uq_projects_name_ci'"
                )
                check_count = await connection.fetchval(
                    "SELECT count(*) FROM pg_constraint WHERE conname IN "
                    "('ck_projects_name_trimmed', 'ck_projects_name_length')"
                )
                return index_count, check_count
            finally:
                await connection.close()

        assert asyncio.run(base_catalog()) == (0, 0)
    finally:
        asyncio.run(drop_database())


def test_migrated_schema_has_no_pending_autogenerated_operations(postgres_database: str) -> None:
    """Missing ORM constraints or indexes must make Alembic detect schema drift."""
    environment = os.environ.copy()
    environment["SUPERBOSS_DATABASE_URL"] = postgres_database

    result = subprocess.run(
        [sys.executable, "-m", "alembic", "check"],
        cwd=SERVER_ROOT,
        env=environment,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr


@pytest.mark.asyncio
async def test_database_rejects_a_second_owner(db_session: AsyncSession) -> None:
    """Removing the partial OWNER index would let two owners commit."""
    db_session.add(User(wecom_userid="owner-1", role=Role.OWNER, status=UserStatus.ACTIVE))
    await db_session.commit()

    db_session.add(User(wecom_userid="owner-2", role=Role.OWNER, status=UserStatus.ACTIVE))
    with pytest.raises(IntegrityError):
        await db_session.commit()
    await db_session.rollback()


@pytest.mark.asyncio
async def test_database_rejects_duplicate_project_membership(db_session: AsyncSession) -> None:
    """Dropping the membership composite unique constraint would allow duplicates."""
    project = Project(name="Core platform")
    user = User(wecom_userid="staff-1", role=Role.STAFF, status=UserStatus.ACTIVE)
    db_session.add_all([project, user])
    await db_session.flush()

    db_session.add_all(
        [
            ProjectMember(project_id=project.id, user_id=user.id),
            ProjectMember(project_id=project.id, user_id=user.id),
        ]
    )
    with pytest.raises(IntegrityError):
        await db_session.commit()
    await db_session.rollback()


def test_project_name_index_compiles_as_a_column_expression() -> None:
    """A string literal expression would make every project collide after the first insert."""
    index = next(index for index in Project.__table__.indexes if index.name == "uq_projects_name_ci")
    compiled = str(CreateIndex(index).compile(dialect=postgresql.dialect()))
    assert "lower(name)" in compiled
    assert "lower('name')" not in compiled


@pytest.mark.asyncio
@pytest.mark.parametrize("name", [" Core ", "\tCore\t", "\rCore\n", "\u00a0Core\u00a0"])
async def test_database_rejects_all_supported_edge_whitespace(
    db_session: AsyncSession, name: str
) -> None:
    """Non-HTTP writers must not bypass canonical edge-whitespace rules."""
    db_session.add(Project(name=name))
    with pytest.raises(IntegrityError):
        await db_session.flush()
    await db_session.rollback()
